[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
eth-rpc-url = "https://arb-mainnet.g.alchemy.com/v2/PeyMa7ljzBjqJxkH6AnLfVH8zRWOtE1n"
# block_number = 220831280
# fork_block_number = 220831280
solc = '0.8.28'
ffi = true
yul = true
via_ir = true
fs_permissions = [{ access = "read-write", path = "./" }]
evm_version = 'shanghai'
gas_reports = ["GmxV2PositionManager", "BasisStrategy"]
show_progress = true
optimizer = true
optimizer_runs = 200
# threads = 1

[rpc_endpoints]
# All available network keywords:
# https://github.com/foundry-rs/forge-std/blob/ff4bf7db008d096ea5a657f2c20516182252a3ed/src/StdCheats.sol#L255-L271
arbitrum_one = "${ARBITRUM_ONE_RPC_URL}"

[invariant]
runs = 16
depth = 256
fail_on_revert = false
