[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
eth-rpc-url = "https://arb-mainnet.g.alchemy.com/v2/PeyMa7ljzBjqJxkH6AnLfVH8zRWOtE1n"
# block_number = 207092188
# fork_block_number = 207092188
solc = '0.8.25'
ffi = true
# yul = true
via_ir = true
fs_permissions = [{ access = "write", path = "./"}]
evm_version = 'shanghai'
gas_reports = ["GmxV2PositionManager"]

[rpc_endpoints]
# All available network keywords:
# https://github.com/foundry-rs/forge-std/blob/ff4bf7db008d096ea5a657f2c20516182252a3ed/src/StdCheats.sol#L255-L271
arbitrum_one = "${ARBITRUM_ONE_RPC_URL}"

[etherscan]
arbitrum_one = { key = "${ARBITRUM_ONE_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
